services:
  app:
    image: smontoya97/franchise-api:latest
    restart: unless-stopped
    expose:
      - "8080"
    env_file:
      - .env.prod
    environment:
      SPRING_PROFILES_ACTIVE: prod

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data

volumes:
  caddy_data: