spring:
  application:
    name: franchise-api
  webflux:
    base-path: /api/v1
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

server:
  port: 8080
