spring:
  application:
    name: franchise-api

  r2dbc:
    url: r2dbc:h2:mem:///franchisedb;DB_CLOSE_DELAY=-1
    username: sa
    password:

  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

server:
  port: 8080

logging:
  level:
    org.springframework.r2dbc: DEBUG