spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/franchisedb
    username: franchise_user
    password: franchise_pass

logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.asyncer.r2dbc.mysql: DEBUG